- name: ownership of a directory
  file:
    path: /opt/tomcat
    state: directory
    recurse: yes 
    group: tomcat 

- name: give the tomcat group read access to the conf
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes 
    mode: g+r 

- name: give the tomcat group exucete access to the conf
  file:
    path: /opt/tomcat/conf
    state: directory
    recurse: yes 
    mode: g+x 

- name: Make the tomcat user the owner of the webapps
  file:
    path: /opt/tomcat/webapps
    state: directory
    recurse: yes 
    owner: tomcat 

- name: Make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp
    state: directory
    recurse: yes 
    owner: tomcat 

- name: Make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs
    state: directory
    recurse: yes 
    owner: tomcat    

    