 
 - name: i want web app that comes with Tomcat
   template:
       src: mytemplates/tomcatuser.j2
       dest: /opt/tomcat/conf/tomcat-users.xml

 - name: i want to copy context file into node side
   template:
        src: mytemplates/context.j2
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml
 
 - name: i want to copy hostcontext file into node side
   template:
        src: mytemplates/hostcontext.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml